default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: api_meu_amig_au_development

test:
  <<: *default
  database: api_meu_amig_au_test

production:
  primary: &primary_production
    <<: *default
    database: api_meu_amig_au_production
    username: api_meu_amig_au
    password: <%= ENV["API_MEU_AMIG_AU_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: api_meu_amig_au_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: api_meu_amig_au_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: api_meu_amig_au_production_cable
    migrations_paths: db/cable_migrate
