name: "Ruby on Rails CI"

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:11-alpine
                ports:
                    - "5432:5432"
                env:
                    POSTGRES_DB: rails_test
                    POSTGRES_USER: rails
                    POSTGRES_PASSWORD: password
        env:
            RAILS_ENV: test
            DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Ruby and gems
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true
                  ruby-version: .ruby-version

            - name: Wait for PostgreSQL to be ready
              run: |
                  until pg_isready -h localhost -p 5432; do
                    echo "Waiting for PostgreSQL..."
                    sleep 1
                  done

            - name: Set up database
              run: |
                  bin/rails db:create
                  bin/rails db:schema:load

            - name: Run tests
              run: bin/rspec

    lint:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Ruby and gems
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true
                  ruby-version: .ruby-version

            - name: Cache Ruby Gems
              uses: actions/cache@v4
              with:
                  path: vendor/bundle
                  key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gem-

            - name: Generate binstubs
              run: bundle binstubs bundler-audit brakeman rubocop

            - name: Security audit dependencies
              run: bin/bundler-audit --update

            - name: Security audit application code
              run: bin/brakeman -q -w2

            - name: Lint Ruby files
              run: bin/rubocop --parallel
